"use client";

import { useMemo, useState } from "react";
import "./discover.css";

const people = [
  {name:"Sofia Chen", handle:"@sofia.builds", city:"San Francisco, US", image:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=85", score:96, niche:"Future of work · B2B", followers:"258K", engagement:"6.8%", reach:"71K", platforms:["in","◎","▶"], tags:["SaaS","Founder audience","US"], growth:"+14.2%"},
  {name:"Jordan Okafor", handle:"@jordanonproduct", city:"London, UK", image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=85", score:94, niche:"Product growth · SaaS", followers:"602K", engagement:"8.2%", reach:"138K", platforms:["▶","in","𝕏"], tags:["Product","B2B","UK"], growth:"+9.1%"},
  {name:"Maya Patel", handle:"@mayamakesmoves", city:"New York, US", image:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=85", score:91, niche:"Startups · Creator economy", followers:"176K", engagement:"11.4%", reach:"59K", platforms:["♪","◎","in"], tags:["Startups","Gen Z","US"], growth:"+22.7%"},
  {name:"Alex Dubois", handle:"@alexfromparis", city:"Paris, France", image:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=85", score:89, niche:"AI · Design systems", followers:"143K", engagement:"7.9%", reach:"41K", platforms:["◎","in","𝕏"], tags:["AI","Design","Europe"], growth:"+8.4%"},
  {name:"Nina Reyes", handle:"@ninaexplains", city:"Austin, US", image:"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=240&q=85", score:87, niche:"No-code · Solopreneur", followers:"311K", engagement:"9.1%", reach:"88K", platforms:["▶","♪","◎"], tags:["No-code","SMB","US"], growth:"+17.5%"},
  {name:"Theo Martin", handle:"@theo.build", city:"Berlin, DE", image:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=85", score:85, niche:"Developer tools · AI", followers:"91K", engagement:"10.2%", reach:"29K", platforms:["𝕏","in","▶"], tags:["Developers","AI","Europe"], growth:"+31.6%"},
  {name:"Amara Nwosu", handle:"@amarathinks", city:"Toronto, CA", image:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&q=85", score:84, niche:"Work culture · Leadership", followers:"224K", engagement:"7.6%", reach:"62K", platforms:["in","◎","▶"], tags:["Leadership","Future of work","Canada"], growth:"+12.8%"},
  {name:"Leo Park", handle:"@leopark.ai", city:"Seoul, KR", image:"https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=240&q=85", score:83, niche:"AI workflows · Automation", followers:"388K", engagement:"8.8%", reach:"116K", platforms:["▶","𝕏","♪"], tags:["Automation","AI","Global"], growth:"+26.4%"},
  {name:"Camille Laurent", handle:"@camilleonbrand", city:"Paris, France", image:"https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=240&q=85", score:82, niche:"Brand strategy · Design", followers:"126K", engagement:"9.4%", reach:"37K", platforms:["◎","in","♪"], tags:["Brand","Design","Europe"], growth:"+15.1%"},
  {name:"Daniel Kim", handle:"@dankimships", city:"Los Angeles, US", image:"https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=240&q=85", score:81, niche:"Indie hacking · Product", followers:"154K", engagement:"12.1%", reach:"49K", platforms:["𝕏","▶","in"], tags:["Indie hackers","Product","US"], growth:"+19.8%"},
  {name:"Isla Morgan", handle:"@islabuilds", city:"Melbourne, AU", image:"https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?auto=format&fit=crop&w=240&q=85", score:80, niche:"Startup operations · SaaS", followers:"82K", engagement:"8.6%", reach:"24K", platforms:["in","◎","𝕏"], tags:["SaaS","Operations","APAC"], growth:"+10.6%"},
  {name:"Mateo Silva", handle:"@mateomakes", city:"Lisbon, PT", image:"https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=240&q=85", score:79, niche:"Creative tools · Video", followers:"274K", engagement:"10.8%", reach:"79K", platforms:["♪","◎","▶"], tags:["Creative","Video","Europe"], growth:"+24.3%"},
  {name:"Priya Shah", handle:"@priyaplays", city:"Bengaluru, IN", image:"https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=240&q=85", score:78, niche:"Community · Growth", followers:"119K", engagement:"9.8%", reach:"36K", platforms:["in","𝕏","▶"], tags:["Community","Growth","APAC"], growth:"+18.9%"}
];

export default function Discover(){
  const [query,setQuery]=useState(""); const [platform,setPlatform]=useState("All"); const [saved,setSaved]=useState<string[]>(["Sofia Chen"]); const [view,setView]=useState("Grid"); const [filter,setFilter]=useState(false); const [toast,setToast]=useState(""); const [collapsed,setCollapsed]=useState(false);
  const results=useMemo(()=>people.filter(p=>(`${p.name} ${p.handle} ${p.niche} ${p.tags.join(" ")}`).toLowerCase().includes(query.toLowerCase())&&(platform==="All"||p.platforms.includes(platform))),[query,platform]);
  const say=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2300)};
  return <main className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">d</span><span>distroa</span></a><div className="workspace-switch"><span className="workspace-dot">A</span><span>Arden Labs</span><span className="chevron">⌄</span></div><nav><p className="nav-label">Workspace</p><a className="nav-item" href="/"><span className="icon">◈</span>Overview</a><a className="nav-item active" href="/discover"><span className="icon">⌁</span>Discover</a><a className="nav-item"><span className="icon">◫</span>Campaigns <span className="nav-count">3</span></a><a className="nav-item"><span className="icon">♧</span>Content studio</a><a className="nav-item"><span className="icon">⌇</span>Analytics</a><p className="nav-label second">Manage</p><a className="nav-item"><span className="icon">◌</span>Creator lists</a><a className="nav-item"><span className="icon">✦</span>AI consultant</a></nav><div className="sidebar-bottom"><button className="ai-card" onClick={()=>say("Distroa AI is ready to build your creator strategy.")}><span className="spark">✦</span><span><b>Ask Distroa AI</b><small>Your distribution partner</small></span><span>→</span></button><div className="profile"><div className="profile-avatar">FA</div><div><b>Farell A.</b><small>Admin</small></div><span>•••</span></div></div></aside>
  <section className="content"><header className="topbar"><div className="crumb">Workspace <span>/</span><b> Creator discovery</b></div><div className="top-actions"><button className="round-button">⌘ K</button><button className="round-button bell">♧<i/></button><button className="new-button" onClick={()=>say("New creator list created.")}>+ Create list</button></div></header><div className="discover-page"><div className="discover-head"><div><p className="eyebrow">CREATOR INTELLIGENCE</p><h1>Discover the right voices.</h1><p className="subhead">Search a living map of people shaping your category.</p></div><button className="ai-match" onClick={()=>say("AI is building a list of 24 high-intent creator matches.")}><span>✦</span><div><b>Let AI find your match</b><small>Based on Arden Labs’ audience</small></div><i>→</i></button></div>
  <div className="discover-search"><label className="big-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creators, topics, companies, or keywords"/><kbd>⌘ K</kbd></label><button className={filter?"filter selected":"filter"} onClick={()=>setFilter(!filter)}>☷ All filters <b>4</b></button></div>
  <div className="discover-main"><aside className={filter?"facet-panel open":"facet-panel"}><div className="facet-title"><b>Filter creators</b><button onClick={()=>setPlatform("All")}>Reset</button></div><div className="facet"><p>Platform</p><div className="platform-checks">{["All","in","◎","▶","♪","𝕏"].map(x=><button key={x} onClick={()=>setPlatform(x)} className={platform===x?"chosen":""}>{x==="All"?"All platforms":x}<span>{x==="All"?"186":x==="in"?"128":x==="◎"?"116":x==="▶"?"93":"76"}</span></button>)}</div></div><div className="facet"><p>Audience size</p><div className="range-line"><i/><i className="right"/></div><div className="range-label"><span>10K</span><span>1M+</span></div></div><div className="facet"><p>Creator topics</p><div className="topic-chips"><button>AI</button><button className="active-chip">SaaS</button><button>Product</button><button>Startups</button><button>Design</button><button>Future of work</button></div></div><div className="facet"><p>Audience location</p><button className="location">⌖ United States <span>⌄</span></button></div></aside>
  <div className="results"><div className="result-top"><p><b>{results.length} creators</b> matched your signals <span>•</span> Sorted by <b>best fit</b></p><div className="view-toggle"><button className={view==="Grid"?"on":""} onClick={()=>setView("Grid")}>▦</button><button className={view==="List"?"on":""} onClick={()=>setView("List")}>☷</button></div></div><div className={view==="Grid"?"discover-grid":"discover-list"}>{results.map(p=><article className="discover-card" key={p.name}><div className="dc-top"><img src={p.image} alt=""/><button className={saved.includes(p.name)?"save saved":"save"} aria-label={`Save ${p.name}`} onClick={()=>setSaved(s=>s.includes(p.name)?s.filter(x=>x!==p.name):[...s,p.name])}>{saved.includes(p.name)?"♥":"♡"}</button><span className="match-score"><b>{p.score}</b> fit</span></div><div className="dc-name"><div><h3>{p.name} <em>✓</em></h3><p>{p.handle} · {p.city}</p></div><div className="multi-platforms">{p.platforms.map((x,i)=><span className={`platform p${i}`} key={x}>{x}</span>)}</div></div><p className="dc-niche">{p.niche}</p><div className="dc-stats"><div><span>Combined following</span><b>{p.followers}</b></div><div><span>Engagement</span><b>{p.engagement}</b></div><div><span>Avg. reach</span><b>{p.reach}</b></div></div><div className="dc-growth"><span>Audience growth</span><b>↗ {p.growth}</b><i/></div><div className="dc-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="dc-actions"><a href={p.name==="Sofia Chen"?"/discover/sofia-chen":"/discover/sofia-chen"}>View profile <span>→</span></a><button onClick={()=>say(`Outreach draft prepared for ${p.name}.`)}>Contact</button></div></article>)}</div>{results.length===0&&<div className="empty-state"><span>⌕</span><b>No creators match that search yet.</b><p>Try a broader topic or reset your filters.</p></div>}</div></div></div></section>{toast&&<div className="toast"><span>✦</span>{toast}</div>}</main>
}
