"use client";

import { useState } from "react";
import "../discover.css";
import "./profile.css";
import "./profile-fix.css";

const posts = [
  { type: "in", image: "/images/product-growth-editorial.png", label: "Product leadership", title: "The 3 things I’d fix before hiring your first growth lead", views: "184K impressions", eng: "9.7% engagement", date: "Sep 8" },
  { type: "▶", image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=900&q=88", label: "Distribution systems", title: "Why the best SaaS teams are rebuilding their distribution", views: "92K views", eng: "8.4% engagement", date: "Sep 4" },
  { type: "◎", image: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=900&q=88", label: "The workday edit", title: "A quiet productivity stack for ambitious teams", views: "71K reach", eng: "11.2% engagement", date: "Aug 28" }
];

function Sidebar({ collapsed, onToggle, onAsk }: { collapsed: boolean; onToggle: () => void; onAsk: () => void }) {
  return <aside className={`sidebar slick-sidebar ${collapsed ? "collapsed" : ""}`}>
    <div className="side-top"><a className="brand" href="/"><span className="brand-mark">d</span><span className="side-copy">distroa</span></a><button className="sidebar-toggle" onClick={onToggle} aria-label={collapsed ? "Open navigation" : "Collapse navigation"}><span className="panel-icon"/></button></div>
    <div className="workspace-switch"><span className="workspace-dot">A</span><span className="side-copy">Arden Labs</span><span className="chevron side-copy">⌄</span></div>
    <nav><p className="nav-label side-copy">Workspace</p><a className="nav-item" href="/" title="Overview"><span className="icon">◈</span><span className="side-copy">Overview</span></a><a className="nav-item active" href="/discover" title="Discover"><span className="icon">⌁</span><span className="side-copy">Discover</span></a><a className="nav-item" title="Campaigns"><span className="icon">◫</span><span className="side-copy">Campaigns</span><span className="nav-count side-copy">3</span></a><a className="nav-item" title="Content studio"><span className="icon">♧</span><span className="side-copy">Content studio</span></a><a className="nav-item" title="Analytics"><span className="icon">⌇</span><span className="side-copy">Analytics</span></a><p className="nav-label second side-copy">Manage</p><a className="nav-item" title="Creator lists"><span className="icon">◌</span><span className="side-copy">Creator lists</span></a><a className="nav-item" title="AI consultant"><span className="icon">✦</span><span className="side-copy">AI consultant</span></a></nav>
    <div className="sidebar-bottom"><button className="ai-card" onClick={onAsk}><span className="spark">✦</span><span className="side-copy"><b>Ask Distroa AI</b><small>Your distribution partner</small></span><span className="side-copy">→</span></button></div>
  </aside>;
}

export default function CreatorProfile() {
  const [tab, setTab] = useState("Overview"); const [toast, setToast] = useState(""); const [collapsed, setCollapsed] = useState(false);
  const say = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  return <main className="app-shell">
    <Sidebar collapsed={collapsed} onToggle={() => setCollapsed(!collapsed)} onAsk={() => say("Distroa AI prepared a collaboration recommendation.")} />
    <section className="content"><header className="topbar"><div className="crumb"><a href="/discover">Discover</a><span>/</span><b>Sofia Chen</b></div><div className="top-actions"><button className="round-button">⌘ K</button><button className="new-button" onClick={() => say("Sofia was added to your Autumn launch list.")}>+ Add to list</button></div></header><div className="profile-page">
      <a className="back-link" href="/discover">← Back to discovery</a>
      <section className="creator-hero"><div className="hero-person"><div className="portrait-wrap"><img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=360&q=85" alt="Sofia Chen" /><i>●</i></div><div><div className="name-row"><h1>Sofia Chen <em>✓</em></h1><span className="profile-fit">96 fit</span></div><p>@sofia.builds <span>·</span> San Francisco, US <span>·</span> Active this week</p><div className="hero-platforms"><span className="platform linkedin">in</span><b>LinkedIn</b><span className="platform instagram">◎</span><b>Instagram</b><span className="platform youtube">▶</span><b>YouTube</b></div></div></div><div className="hero-actions"><button className="button-quiet" onClick={() => say("Sofia saved to your creator list.")}>♡ Save</button><button className="button-dark" onClick={() => say("A personalized outreach email is ready for review.")}>✉ Contact Sofia</button><button className="more">•••</button></div></section>
      <section className="profile-tabs">{["Overview", "Audience", "Content", "Partnerships"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</section>
      {tab !== "Overview" ? <div className="tab-placeholder"><span>✦</span><h2>{tab} intelligence</h2><p>This demo keeps the complete {tab.toLowerCase()} dataset ready for the next prototype screen.</p></div> : <section className="profile-layout"><div><div className="fit-callout"><div className="fit-orb">96</div><div><p className="eyebrow">DISTROA FIT ANALYSIS</p><h2>An exceptional match for Arden Labs.</h2><p>Sofia’s audience and point of view align strongly with your launch audience. Her content consistently earns meaningful discussion—not just reach.</p></div><button onClick={() => say("AI collaboration plan generated for Sofia.")}>View AI rationale →</button></div><div className="metric-row"><div><span>Combined following</span><b>258K</b><small>Across 3 platforms</small></div><div><span>Avg. engagement</span><b>6.8%</b><small className="positive">↗ Top 12% of peers</small></div><div><span>Avg. post reach</span><b>71.4K</b><small>Last 90 days</small></div><div><span>Est. rate</span><b>$3.5–5K</b><small>Integrated post</small></div></div>
        <section className="content-performance"><div className="section-title compact"><div><p className="eyebrow">CONTENT INTELLIGENCE</p><h2>What’s performing now</h2><p>Her top content from the last 30 days.</p></div><a href="#">View all 20 posts →</a></div><div className="post-grid">{posts.map((post) => <article className="post-card polished-post" key={post.title}><div className="post-cover"><img src={post.image} alt="" /><div className="post-gradient" /><span className="platform">{post.type}</span><span className="post-label">{post.label}</span><button onClick={() => say(`Opening the post: “${post.title}”`)}>View post ↗</button></div><p>{post.title}</p><div><span>{post.views}</span><span>{post.eng}</span><time>{post.date}</time></div></article>)}</div></section></div>
        <aside className="profile-aside"><section className="aside-card"><p className="eyebrow">AUDIENCE SNAPSHOT</p><h3>Operators & builders</h3><p className="aside-copy">An engaged audience of product leaders, startup operators, and curious founders.</p><div className="audience-bar"><span>United States</span><b>62%</b><i><em style={{ width: "62%" }} /></i></div><div className="audience-bar"><span>United Kingdom</span><b>14%</b><i><em style={{ width: "14%" }} /></i></div><div className="audience-bar"><span>Canada</span><b>8%</b><i><em style={{ width: "8%" }} /></i></div><button className="aside-action" onClick={() => setTab("Audience")}>Explore audience <span>→</span></button></section><section className="aside-card"><p className="eyebrow">PARTNERSHIP HISTORY</p><div className="brand-history"><span>◩</span><div><b>Notion</b><small>Sponsored content · May 2026</small></div></div><div className="brand-history"><span>△</span><div><b>Webflow</b><small>Ambassador series · Jan 2026</small></div></div><button className="aside-action" onClick={() => setTab("Partnerships")}>View partnership history <span>→</span></button></section><section className="aside-card deal-next"><p className="eyebrow">NEXT BEST ACTION</p><h3>Start a founder-story collaboration.</h3><p className="aside-copy">A YouTube + LinkedIn package has the highest projected resonance.</p><button className="button-dark" onClick={() => say("Campaign brief created with Sofia as the first creator.")}>Create campaign brief</button></section></aside></section>}
    </div></section>{toast && <div className="toast"><span>✦</span>{toast}</div>}</main>;
}
