"use client";
import { useState } from "react";
import AppSidebar from "../components/AppSidebar";
import ProductTopbar from "../components/ProductTopbar";
import "./studio.css";

const items = [
  { creator:"Jordan Okafor", initials:"JO", format:"YouTube · 08:42", title:"Why modern SaaS teams are rebuilding distribution", status:"Needs review", due:"Today", color:"blue", image:"https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=760&q=85" },
  { creator:"Sofia Chen", initials:"SC", format:"LinkedIn · Carousel", title:"Three systems behind a calmer product launch", status:"Approved", due:"Sep 30", color:"sage", image:"/images/product-growth-editorial.png" },
  { creator:"Maya Patel", initials:"MP", format:"TikTok · 00:38", title:"The creator stack I wish I had last year", status:"Draft", due:"Oct 03", color:"peach", image:"https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=760&q=85" }
];
export default function ContentStudio(){const [selected,setSelected]=useState(0);const [toast,setToast]=useState("");const [tab,setTab]=useState("All");const say=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};const visible=tab==="All"?items:items.filter(x=>x.status===tab);return <main className="app-shell"><AppSidebar active="content"/><section className="content"><ProductTopbar page="Content studio" action="New content brief" onAction={()=>say("New content brief created.")}/><div className="product-page"><div className="product-head"><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>Ship work worth sharing.</h1><p className="subhead">Review creator drafts, centralize feedback, and protect the publishing rhythm.</p></div><div className="product-head-actions"><button className="quiet-button" onClick={()=>say("Calendar view opened.")}>Calendar</button><button className="quiet-button" onClick={()=>say("Assets library opened.")}>Assets library</button></div></div><div className="studio-layout"><section className="product-panel studio-queue"><div className="panel-heading"><div><h2>Content queue</h2><p>6 deliverables across 3 campaigns.</p></div><div className="segmented">{["All","Needs review","Approved"].map(x=><button key={x} className={tab===x?"on":""} onClick={()=>setTab(x)}>{x}</button>)}</div></div><div className="queue-list">{visible.map((item,index)=><button key={item.title} className={`queue-item ${selected===items.indexOf(item)?"selected":""}`} onClick={()=>setSelected(items.indexOf(item))}><img src={item.image} alt=""/><div><span>{item.format}</span><b>{item.title}</b><small>{item.creator} · Due {item.due}</small></div><em className={item.color}>{item.status}</em></button>)}</div></section><section className="product-panel review-pane"><div className="review-cover"><img src={items[selected].image} alt="Content preview"/><span>Preview</span><button>▶</button></div><p className="eyebrow">{items[selected].format.toUpperCase()}</p><h2>{items[selected].title}</h2><div className="review-author"><i>{items[selected].initials}</i><span><b>{items[selected].creator}</b><small>Submitted 42 minutes ago</small></span></div><div className="review-note"><b>Creator note</b><p>Kept the opening direct and used the product naturally in the second beat. Would love your read on the final CTA.</p></div><textarea aria-label="Feedback" placeholder="Leave precise, useful feedback…"/><div className="review-actions"><button onClick={()=>say("Changes requested with your feedback.")}>Request changes</button><button className="button-dark" onClick={()=>say("Content approved for publishing.")}>Approve content</button></div></section></div></div></section>{toast&&<div className="toast"><span>✦</span>{toast}</div>}</main>}
