"use client";

import { useState } from "react";
import "./campaigns.css";
import "./campaign-fix.css";

const campaigns = [
  { title: "Autumn product launch", stage: "In flight", color: "sage", spend: "$12,400", reach: "1.28M", progress: 72, creators: ["SC", "JO", "MP"], due: "Oct 02" },
  { title: "Founder story series", stage: "In review", color: "blue", spend: "$6,800", reach: "486K", progress: 48, creators: ["JO", "AD"], due: "Oct 08" },
  { title: "Creator tools push", stage: "Briefing", color: "peach", spend: "$3,250", reach: "312K", progress: 22, creators: ["MP", "NR"], due: "Oct 16" }
];

const pipeline = [
  { name: "Sofia Chen", role: "LinkedIn thought-leadership", state: "Script approved", date: "Publishing Sep 30", initials: "SC", tone: "sage" },
  { name: "Jordan Okafor", role: "YouTube founder interview", state: "Needs your review", date: "Due today", initials: "JO", tone: "blue" },
  { name: "Maya Patel", role: "Short-form product story", state: "Brief sent", date: "Due Oct 03", initials: "MP", tone: "peach" },
  { name: "Alex Dubois", role: "Design systems carousel", state: "Negotiating", date: "Follow up tomorrow", initials: "AD", tone: "lilac" }
];

export default function Campaigns() {
  const [selected, setSelected] = useState(0); const [toast, setToast] = useState("");
  const say = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  return <main className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">d</span><span>distroa</span></a><div className="workspace-switch"><span className="workspace-dot">A</span><span>Arden Labs</span><span className="chevron">⌄</span></div><nav><p className="nav-label">Workspace</p><a className="nav-item" href="/"><span className="icon">◈</span>Overview</a><a className="nav-item" href="/discover"><span className="icon">⌁</span>Discover</a><a className="nav-item active" href="/campaigns"><span className="icon">◫</span>Campaigns <span className="nav-count">3</span></a><a className="nav-item"><span className="icon">♧</span>Content studio</a><a className="nav-item"><span className="icon">⌇</span>Analytics</a><p className="nav-label second">Manage</p><a className="nav-item"><span className="icon">◌</span>Creator lists</a><a className="nav-item"><span className="icon">✦</span>AI consultant</a></nav><div className="sidebar-bottom"><button className="ai-card" onClick={() => say("Distroa AI is ready to shape your next campaign.")}><span className="spark">✦</span><span><b>Ask Distroa AI</b><small>Your distribution partner</small></span><span>→</span></button><div className="profile"><div className="profile-avatar">FA</div><div><b>Farell A.</b><small>Admin</small></div><span>•••</span></div></div></aside>
  <section className="content"><header className="topbar"><div className="crumb">Workspace <span>/</span><b> Campaigns</b></div><div className="top-actions"><button className="round-button">⌘ K</button><button className="round-button bell">♧<i /></button><button className="new-button" onClick={() => say("A blank campaign brief is ready.")}>+ New campaign</button></div></header><div className="campaign-page"><div className="campaign-heading"><div><p className="eyebrow">CAMPAIGN COMMAND CENTER</p><h1>Make every collaboration count.</h1><p className="subhead">Plan the work, keep momentum, and see what’s moving the needle.</p></div><button className="strategy-card" onClick={() => say("AI found two creators to strengthen your launch reach.")}><span>✦</span><div><b>Campaign health is strong</b><small>2 opportunities need attention</small></div><i>→</i></button></div>
  <div className="campaign-stats"><div><span>Active campaigns</span><b>3</b><small>+1 this month</small></div><div><span>Creators in motion</span><b>12</b><small>Across 4 platforms</small></div><div><span>Committed spend</span><b>$22.4K</b><small>68% of monthly budget</small></div><div><span>Projected reach</span><b>2.1M</b><small>↗ 18% vs. last month</small></div></div>
  <section className="campaign-section"><div className="section-title"><div><h2>Your active campaigns</h2><p>Click a campaign to focus the command center.</p></div><button className="link-button" onClick={() => say("Archived campaigns are up to date.")}>View archive →</button></div><div className="campaign-grid">{campaigns.map((campaign, index) => <button className={`campaign-card ${campaign.color} ${selected === index ? "selected" : ""}`} key={campaign.title} onClick={() => setSelected(index)}><div className="campaign-card-top"><span className={`campaign-stage ${campaign.color}`}>{campaign.stage}</span><span>•••</span></div><h3>{campaign.title}</h3><div className="campaign-avatars">{campaign.creators.map((creator) => <i key={creator}>{creator}</i>)}<small>+{index + 2}</small></div><div className="campaign-numbers"><span><b>{campaign.spend}</b> spend</span><span><b>{campaign.reach}</b> projected reach</span></div><div className="campaign-progress"><i style={{ width: `${campaign.progress}%` }} /></div><div className="campaign-footer"><span>{campaign.progress}% complete</span><b>Due {campaign.due} →</b></div></button>)}</div></section>
  <section className="focus-panel"><div className="focus-title"><div><p className="eyebrow">NOW FOCUSING</p><h2>{campaigns[selected].title}</h2><span className={`campaign-stage ${campaigns[selected].color}`}>{campaigns[selected].stage}</span></div><div className="focus-actions"><button onClick={() => say("Campaign brief opened.")}>View brief</button><button className="button-dark" onClick={() => say("Creator has been added to this campaign.")}>+ Add creator</button></div></div><div className="focus-grid"><div className="pipeline"><div className="panel-head"><div><h3>Creator pipeline</h3><p>Keep each deliverable moving.</p></div><button onClick={() => say("All creator deliverables are visible below.")}>See all →</button></div>{pipeline.map((item) => <div className="pipeline-row" key={item.name}><div className={`pipeline-avatar ${item.tone}`}>{item.initials}</div><div className="pipeline-info"><b>{item.name}</b><span>{item.role}</span></div><span className={`pipeline-state ${item.tone}`}>{item.state}</span><time>{item.date}</time><button onClick={() => say(`Opening ${item.name}’s collaboration.`)}>→</button></div>)}</div><aside className="next-action"><p className="eyebrow">NEXT BEST ACTION</p><div className="action-orb">2</div><h3>Review Jordan’s video cut.</h3><p>The launch window is approaching. Your feedback today keeps the YouTube story on track.</p><button className="button-dark" onClick={() => say("Jordan’s video review is open.")}>Review content →</button><small>Due in 4 hours</small></aside></div></section></div></section>{toast && <div className="toast"><span>✦</span>{toast}</div>}</main>;
}
